language: node_js
deploy:
  provider: npm
  email: paukan.control@gmail.com
  api_key:
    secure: JCRrTwX1ceCX6LcgML+Tlqkp887ofGwAbOq8fyoH5tWzITAqIyRdXGu5XqfPIIKMvlYwUfY4Lrfnni5TKtuvJqLFOr0V0yi0UJWuqUabJRKlw5DieN24sLc0DWTZ3/+3N12i/kxtKFPUunVUxBTWwP4LxT0WaiRKKxvffJoRUGU=
  on:
    repo: paukan-org/ifttt
